# MongoDB Atlas — independent module with its own state.
# Lives outside terraform/core so the cluster persists across
# core+agents teardown/redeploy. Apply this module FIRST when
# bootstrapping a new environment.

variable "atlas_public_key" {
  description = "Atlas Admin API public key (PAK), shared with ASP setup"
  type        = string
  sensitive   = true
}

variable "atlas_private_key" {
  description = "Atlas Admin API private key (PAK), shared with ASP setup"
  type        = string
  sensitive   = true
}

variable "atlas_project_id" {
  description = "Existing Atlas project ID where the cluster will be created"
  type        = string
}

variable "atlas_cluster_name" {
  description = "Name for the Atlas cluster"
  type        = string
  default     = "streaming-agents-cluster"
}

variable "atlas_db_username" {
  description = "Database username created with the cluster"
  type        = string
  default     = "streaming_agents_app"
}

variable "atlas_db_password" {
  description = "Database password (generated by deploy.py)"
  type        = string
  sensitive   = true
}

variable "cloud_region" {
  description = "AWS region (mapped to Atlas region: us-east-1 -> US_EAST_1)"
  type        = string
  default     = "us-east-1"
}

variable "owner_email" {
  description = "Owner email for resource tagging"
  type        = string
  default     = ""
}

# Atlas IP access list CIDRs. Workshop mode passes
# ["0.0.0.0/0"] (the legacy default). Non-workshop deploys pass the
# deployer's egress IP as a /32, dramatically reducing the public
# blast radius.
variable "atlas_access_cidrs" {
  description = <<-EOT
    CIDR block(s) allowed to connect to the Atlas cluster. Defaults to
    0.0.0.0/0 (workshop convenience). Override to scope to the
    deployer's egress IP (`<X.X.X.X>/32`) for non-workshop deployments.
  EOT
  type        = list(string)
  default     = ["0.0.0.0/0"]
}
